version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www
    # sqlite:
    #   image: nouchka/sqlite3:latest
    #   stdin_open: true
    #   tty: true
    #   volumes:
    #     - ./database:/var/www/database
    # depends_on:
    #   - database
  # database:
    # No need for an image definition for SQLite
    # volumes:
    #   - ./database:/var/www/database



