version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "8000:9000"
    env_file: .env
    working_dir: /var/www/html
    volumes:
      - ./mytodo:/var/www/html
    # command: bash -c 'php artisan migrate && php artisan serve --host 127.0.0.1'
    # depends_on:
    #   - database

  # database:
  #   image: mysql:5.7
  #   environment:
  #     MYSQL_DATABASE: laravel
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: secret
  #     MYSQL_ROOT_PASSWORD: secret
  #   volumes:
  #     - ./mysql:/var/lib/mysql


  # database:
  #   # No need for an image definition for SQLite
  #   volumes:
  #     - ./database:/var/www/database