version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www
    depends_on:
      - database
  database:
    image: "sqlite:latest"
    volumes:
      - .\database:/var/www/database